# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
    ]
